/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IReputationToken,
  IReputationTokenInterface,
} from "../../../contracts/Escrow.sol/IReputationToken";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "agent",
        type: "address",
      },
    ],
    name: "recordFailure",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "agent",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "payoutAmount",
        type: "uint256",
      },
    ],
    name: "recordSuccess",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IReputationToken__factory {
  static readonly abi = _abi;
  static createInterface(): IReputationTokenInterface {
    return new Interface(_abi) as IReputationTokenInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IReputationToken {
    return new Contract(address, _abi, runner) as unknown as IReputationToken;
  }
}
