/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IOrderBook {
  export type JobInfoStruct = {
    id: BigNumberish;
    poster: AddressLike;
    provider: AddressLike;
    metadataURI: string;
    maxBudgetUsdc: BigNumberish;
    deadline: BigNumberish;
    status: BigNumberish;
    deliveryProof: BytesLike;
    createdAt: BigNumberish;
    acceptedBidId: BigNumberish;
  };

  export type JobInfoStructOutput = [
    id: bigint,
    poster: string,
    provider: string,
    metadataURI: string,
    maxBudgetUsdc: bigint,
    deadline: bigint,
    status: bigint,
    deliveryProof: string,
    createdAt: bigint,
    acceptedBidId: bigint
  ] & {
    id: bigint;
    poster: string;
    provider: string;
    metadataURI: string;
    maxBudgetUsdc: bigint;
    deadline: bigint;
    status: bigint;
    deliveryProof: string;
    createdAt: bigint;
    acceptedBidId: bigint;
  };
}

export interface IOrderBookInterface extends Interface {
  getFunction(nameOrSignature: "getJob" | "markReleased"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getJob",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "markReleased",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "getJob", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "markReleased",
    data: BytesLike
  ): Result;
}

export interface IOrderBook extends BaseContract {
  connect(runner?: ContractRunner | null): IOrderBook;
  waitForDeployment(): Promise<this>;

  interface: IOrderBookInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getJob: TypedContractMethod<
    [jobId: BigNumberish],
    [IOrderBook.JobInfoStructOutput],
    "view"
  >;

  markReleased: TypedContractMethod<
    [jobId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getJob"
  ): TypedContractMethod<
    [jobId: BigNumberish],
    [IOrderBook.JobInfoStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "markReleased"
  ): TypedContractMethod<[jobId: BigNumberish], [void], "nonpayable">;

  filters: {};
}
