/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IOrderBook,
  IOrderBookInterface,
} from "../../../contracts/Escrow.sol/IOrderBook";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "jobId",
        type: "uint256",
      },
    ],
    name: "getJob",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "id",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "poster",
            type: "address",
          },
          {
            internalType: "address",
            name: "provider",
            type: "address",
          },
          {
            internalType: "string",
            name: "metadataURI",
            type: "string",
          },
          {
            internalType: "uint256",
            name: "maxBudgetUsdc",
            type: "uint256",
          },
          {
            internalType: "uint64",
            name: "deadline",
            type: "uint64",
          },
          {
            internalType: "uint8",
            name: "status",
            type: "uint8",
          },
          {
            internalType: "bytes32",
            name: "deliveryProof",
            type: "bytes32",
          },
          {
            internalType: "uint256",
            name: "createdAt",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "acceptedBidId",
            type: "uint256",
          },
        ],
        internalType: "struct IOrderBook.JobInfo",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "jobId",
        type: "uint256",
      },
    ],
    name: "markReleased",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IOrderBook__factory {
  static readonly abi = _abi;
  static createInterface(): IOrderBookInterface {
    return new Interface(_abi) as IOrderBookInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IOrderBook {
    return new Contract(address, _abi, runner) as unknown as IOrderBook;
  }
}
