/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IOrderBook,
  IOrderBookInterface,
} from "../../../contracts/Escrow.sol/IOrderBook";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "jobId",
        type: "uint256",
      },
    ],
    name: "markReleased",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IOrderBook__factory {
  static readonly abi = _abi;
  static createInterface(): IOrderBookInterface {
    return new Interface(_abi) as IOrderBookInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IOrderBook {
    return new Contract(address, _abi, runner) as unknown as IOrderBook;
  }
}
